### ISSUE TITLE
Please, update your awesome addons for Anki 2.1.x branch.

### ISSUE THREAD

**Issue by JulyMorning** [luminousspice/anki-addons#2]
you can download it here:

— https://anki.tenderapp.com/discussions/beta-testing

**Comment by luminousspice** [comment]
All of my add-ons are ready for Anki 2.1.x now, except for "Find Mature". Please see the [README](https://github.com/luminousspice/anki-addons/blob/master/README.md)
Sidebar is removed from Card Browser at Beta 11, so I can't keep Find Mature.
