### ISSUE TITLE
I forked the Straight Reward add-on

### ISSUE THREAD

**Issue by hgiesel** [luminousspice/anki-addons#8]
Hi,
I really liked the idea of your Straight Reward addon, but wanted to add some of my own features. I also noticed that you don't seem to have the time anymore for maintaining the add-on. That's why I've created a fork [here](https://github.com/hgiesel/anki_straight_reward). I credited you as the originator of the add-on.

Hope you have a nice day,
Henrik

**Comment by luminousspice** [comment]
Hi Henrik,
Thank you for the notice. Good Luck.
- Luminous
